//
//  HardEmoji.swift
//  Swipe
//
//  Created by Jesus Andres Bernal Lopez on 3/30/18.
//  Copyright © 2018 Jesus Andres Bernal Lopez. All rights reserved.
//

import UIKit

class FlagEmoji {
    
    var list = [FlagEmojiSelector]()
    
    init(){
        list.append(FlagEmojiSelector("🇦🇫", "afghanistan"))
        list.append(FlagEmojiSelector("🇦🇽", "aland islands"))
        list.append(FlagEmojiSelector("🇦🇱", "albania"))
        list.append(FlagEmojiSelector("🇩🇿", "algeria"))
        list.append(FlagEmojiSelector("🇦🇸", "american samoa"))
        list.append(FlagEmojiSelector("🇦🇩", "andorra"))
        list.append(FlagEmojiSelector("🇦🇴", "angola"))
        list.append(FlagEmojiSelector("🇦🇮", "anguilla"))
        list.append(FlagEmojiSelector("🇦🇶", "antartica"))
        list.append(FlagEmojiSelector("🇦🇬", "antigua and barbuda"))
        list.append(FlagEmojiSelector("🇦🇷", "argentina"))
        list.append(FlagEmojiSelector("🇦🇲", "armenia"))
        list.append(FlagEmojiSelector("🇦🇼", "aruba"))
        list.append(FlagEmojiSelector("🇦🇺", "australia"))
        list.append(FlagEmojiSelector("🇦🇹", "austria"))
        list.append(FlagEmojiSelector("🇦🇿", "azerbaijan"))
        list.append(FlagEmojiSelector("🇧🇸", "bahamas"))
        list.append(FlagEmojiSelector("🇧🇭", "bahrain"))
        list.append(FlagEmojiSelector("🇧🇩", "bangladesh"))
        list.append(FlagEmojiSelector("🇧🇧", "barbados"))
        list.append(FlagEmojiSelector("🇧🇾", "belarus"))
        list.append(FlagEmojiSelector("🇧🇪", "belgium"))
        list.append(FlagEmojiSelector("🇧🇿", "belize"))
        list.append(FlagEmojiSelector("🇧🇯", "benin"))
        list.append(FlagEmojiSelector("🇧🇲", "bermuda"))
        list.append(FlagEmojiSelector("🇧🇹", "bhutan"))
        list.append(FlagEmojiSelector("🇧🇴", "bolivia"))
        list.append(FlagEmojiSelector("🇧🇦", "bosnia and herzegovina"))
        list.append(FlagEmojiSelector("🇧🇼", "botswana"))
        list.append(FlagEmojiSelector("🇧🇷", "brazil"))
        list.append(FlagEmojiSelector("🇮🇴", "british indian ocean territory"))
        list.append(FlagEmojiSelector("🇻🇬", "british virgin islands"))
        list.append(FlagEmojiSelector("🇧🇳", "brunei"))
        list.append(FlagEmojiSelector("🇧🇬", "bulgaria"))
        list.append(FlagEmojiSelector("🇧🇫", "burkina faso"))
        list.append(FlagEmojiSelector("🇧🇮", "burundi"))
        list.append(FlagEmojiSelector("🇰🇭", "cambodia"))
        list.append(FlagEmojiSelector("🇨🇲", "cameroon"))
        list.append(FlagEmojiSelector("🇨🇦", "canada"))
        list.append(FlagEmojiSelector("🇮🇨", "canary islands"))
        list.append(FlagEmojiSelector("🇨🇻", "cape verde"))
        list.append(FlagEmojiSelector("🇧🇶", "caribbean netherlands"))
        list.append(FlagEmojiSelector("🇰🇾", "cayman islands"))
        list.append(FlagEmojiSelector("🇨🇫", "central african republic"))
        list.append(FlagEmojiSelector("🇹🇩", "chad"))
        list.append(FlagEmojiSelector("🇨🇱", "chile"))
        list.append(FlagEmojiSelector("🇨🇳", "china"))
        list.append(FlagEmojiSelector("🇨🇽", "christmas island"))
        list.append(FlagEmojiSelector("🇨🇨", "cocos islands"))
        list.append(FlagEmojiSelector("🇨🇴", "colombia"))
        list.append(FlagEmojiSelector("🇰🇲", "comoros"))
        list.append(FlagEmojiSelector("🇨🇬", "congo brazzaville"))
        list.append(FlagEmojiSelector("🇨🇩", "congo kinshasa"))
        list.append(FlagEmojiSelector("🇨🇰", "cook islands"))
        list.append(FlagEmojiSelector("🇨🇷", "costa rica"))
        list.append(FlagEmojiSelector("🇨🇮", "ivory coast"))
        list.append(FlagEmojiSelector("🇭🇷", "croatia"))
        list.append(FlagEmojiSelector("🇨🇺", "cuba"))
        list.append(FlagEmojiSelector("🇨🇼", "curacao"))
        list.append(FlagEmojiSelector("🇨🇾", "cyprus"))
        list.append(FlagEmojiSelector("🇨🇿", "czechia"))
        list.append(FlagEmojiSelector("🇩🇰", "denmark"))
        list.append(FlagEmojiSelector("🇩🇯", "djibouti"))
        list.append(FlagEmojiSelector("🇩🇲", "dominica"))
        list.append(FlagEmojiSelector("🇩🇴", "dominican republic"))
        list.append(FlagEmojiSelector("🇪🇨", "ecuador"))
        list.append(FlagEmojiSelector("🇪🇬", "egypt"))
        list.append(FlagEmojiSelector("🇸🇻", "el salvador"))
        list.append(FlagEmojiSelector("🇬🇶", "equatorial"))
        list.append(FlagEmojiSelector("🇪🇷", "eritrea"))
        list.append(FlagEmojiSelector("🇪🇪", "estonia"))
        list.append(FlagEmojiSelector("🇪🇹", "ethiopia"))
        list.append(FlagEmojiSelector("🇫🇰", "falkland islands"))
        list.append(FlagEmojiSelector("🇫🇴", "faroe islands"))
        list.append(FlagEmojiSelector("🇫🇯", "fiji"))
        list.append(FlagEmojiSelector("🇫🇮", "finland"))
        list.append(FlagEmojiSelector("🇫🇷", "france"))
        list.append(FlagEmojiSelector("🇬🇫", "french guiana"))
        list.append(FlagEmojiSelector("🇵🇫", "french polynesia"))
        list.append(FlagEmojiSelector("🇹🇫", "french southern territories"))
        list.append(FlagEmojiSelector("🇬🇦", "gabon"))
        list.append(FlagEmojiSelector("🇬🇲", "gambia"))
        list.append(FlagEmojiSelector("🇬🇪", "georgia"))
        list.append(FlagEmojiSelector("🇩🇪", "germany"))
        list.append(FlagEmojiSelector("🇬🇭", "ghana"))
        list.append(FlagEmojiSelector("🇬🇮", "gibraltar"))
        list.append(FlagEmojiSelector("🇬🇷", "greece"))
        list.append(FlagEmojiSelector("🇬🇱", "greenland"))
        list.append(FlagEmojiSelector("🇬🇩", "grenada"))
        list.append(FlagEmojiSelector("🇬🇵", "guadeloupe"))
        list.append(FlagEmojiSelector("🇬🇺", "guam"))
        list.append(FlagEmojiSelector("🇬🇹", "guatemala"))
        list.append(FlagEmojiSelector("🇬🇬", "guernsey"))
        list.append(FlagEmojiSelector("🇬🇳", "guinea"))
        list.append(FlagEmojiSelector("🇬🇼", "guinea bissau"))
        list.append(FlagEmojiSelector("🇬🇾", "guyana"))
        list.append(FlagEmojiSelector("🇭🇹", "haiti"))
        list.append(FlagEmojiSelector("🇭🇳", "honduras"))
        list.append(FlagEmojiSelector("🇭🇺", "hungary"))
        list.append(FlagEmojiSelector("🇮🇸", "iceland"))
        list.append(FlagEmojiSelector("🇮🇳", "india"))
        list.append(FlagEmojiSelector("🇮🇩", "indonesia"))
        list.append(FlagEmojiSelector("🇮🇷", "iran"))
        list.append(FlagEmojiSelector("🇮🇶", "iraq"))
        list.append(FlagEmojiSelector("🇮🇪", "ireland"))
        list.append(FlagEmojiSelector("🇮🇲", "isle of man"))
        list.append(FlagEmojiSelector("🇮🇱", "israel"))
        list.append(FlagEmojiSelector("🇮🇹", "italy"))
        list.append(FlagEmojiSelector("🇯🇲", "jamaica"))
        list.append(FlagEmojiSelector("🇯🇵", "japan"))
        list.append(FlagEmojiSelector("🇯🇪", "jersey"))
        list.append(FlagEmojiSelector("🇯🇴", "jordan"))
        list.append(FlagEmojiSelector("🇰🇿", "kazakhstan"))
        list.append(FlagEmojiSelector("🇰🇪", "kenya"))
        list.append(FlagEmojiSelector("🇰🇮", "kiribati"))
        list.append(FlagEmojiSelector("🇽🇰", "kosovo"))
        list.append(FlagEmojiSelector("🇰🇼", "kuwait"))
        list.append(FlagEmojiSelector("🇰🇬", "kyrgyztan"))
        list.append(FlagEmojiSelector("🇱🇦", "laos"))
        list.append(FlagEmojiSelector("🇱🇻", "latvia"))
        list.append(FlagEmojiSelector("🇱🇧", "lebanon"))
        list.append(FlagEmojiSelector("🇱🇸", "lesotho"))
        list.append(FlagEmojiSelector("🇱🇷", "liberia"))
        list.append(FlagEmojiSelector("🇱🇾", "libya"))
        list.append(FlagEmojiSelector("🇱🇮", "liechtenstein"))
        list.append(FlagEmojiSelector("🇱🇹", "lithuania"))
        list.append(FlagEmojiSelector("🇱🇺", "luxembourg"))
        list.append(FlagEmojiSelector("🇲🇰", "macedonia"))
        list.append(FlagEmojiSelector("🇲🇬", "madagascar"))
        list.append(FlagEmojiSelector("🇲🇼", "malawai"))
        list.append(FlagEmojiSelector("🇲🇾", "malaysia"))
        list.append(FlagEmojiSelector("🇲🇻", "maldives"))
        list.append(FlagEmojiSelector("🇲🇱", "mali"))
        list.append(FlagEmojiSelector("🇲🇹", "malta"))
        list.append(FlagEmojiSelector("🇲🇭", "marshall islands"))
        list.append(FlagEmojiSelector("🇲🇶", "martinique"))
        list.append(FlagEmojiSelector("🇲🇷", "mauritania"))
        list.append(FlagEmojiSelector("🇲🇺", "mauritius"))
        list.append(FlagEmojiSelector("🇾🇹", "mayotte"))
        list.append(FlagEmojiSelector("🇲🇽", "mexico"))
        list.append(FlagEmojiSelector("🇫🇲", "micronesia"))
        list.append(FlagEmojiSelector("🇲🇩", "moldova"))
        list.append(FlagEmojiSelector("🇲🇨", "monaco"))
        list.append(FlagEmojiSelector("🇲🇳", "mongolia"))
        list.append(FlagEmojiSelector("🇲🇪", "montenegro"))
        list.append(FlagEmojiSelector("🇲🇸", "montserrat"))
        list.append(FlagEmojiSelector("🇲🇦", "morocco"))
        list.append(FlagEmojiSelector("🇲🇿", "mozambique"))
        list.append(FlagEmojiSelector("🇲🇲", "myanmar"))
        list.append(FlagEmojiSelector("🇳🇦", "namibia"))
        list.append(FlagEmojiSelector("🇳🇷", "nauru"))
        list.append(FlagEmojiSelector("🇳🇵", "nepal"))
        list.append(FlagEmojiSelector("🇳🇱", "netherlands"))
        list.append(FlagEmojiSelector("🇳🇨", "new caledonia"))
        list.append(FlagEmojiSelector("🇳🇿", "new zealand"))
        list.append(FlagEmojiSelector("🇳🇮", "nicaragua"))
        list.append(FlagEmojiSelector("🇳🇪", "niger"))
        list.append(FlagEmojiSelector("🇳🇬", "nigeria"))
        list.append(FlagEmojiSelector("🇳🇺", "niue"))
        list.append(FlagEmojiSelector("🇳🇫", "norfolk island"))
        list.append(FlagEmojiSelector("🇰🇵", "north korea"))
        list.append(FlagEmojiSelector("🇲🇵", "northern mariana islands"))
        list.append(FlagEmojiSelector("🇳🇴", "norway"))
        list.append(FlagEmojiSelector("🇴🇲", "oman"))
        list.append(FlagEmojiSelector("🇵🇰", "pakistan"))
        list.append(FlagEmojiSelector("🇵🇼", "palau"))
        list.append(FlagEmojiSelector("🇵🇸", "palestinian territories"))
        list.append(FlagEmojiSelector("🇵🇦", "panama"))
        list.append(FlagEmojiSelector("🇵🇬", "papua new guinea"))
        list.append(FlagEmojiSelector("🇵🇾", "paraguay"))
        list.append(FlagEmojiSelector("🇵🇪", "peru"))
        list.append(FlagEmojiSelector("🇵🇭", "philippines"))
        list.append(FlagEmojiSelector("🇵🇳", "pitcairn"))
        list.append(FlagEmojiSelector("🇵🇱", "poland"))
        list.append(FlagEmojiSelector("🇵🇹", "portugal"))
        list.append(FlagEmojiSelector("🇵🇷", "puerto rico"))
        list.append(FlagEmojiSelector("🇶🇦", "qatar"))
        list.append(FlagEmojiSelector("🇷🇪", "reunion"))
        list.append(FlagEmojiSelector("🇷🇴", "romania"))
        list.append(FlagEmojiSelector("🇷🇺", "russia"))
        list.append(FlagEmojiSelector("🇷🇼", "rwanda"))
        list.append(FlagEmojiSelector("🇼🇸", "samoa"))
        list.append(FlagEmojiSelector("🇸🇲", "san marino"))
        list.append(FlagEmojiSelector("🇸🇹", "sao tome and principe"))
        list.append(FlagEmojiSelector("🇸🇦", "saudi arabia"))
        list.append(FlagEmojiSelector("🇸🇳", "senegal"))
        list.append(FlagEmojiSelector("🇷🇸", "serbia"))
        list.append(FlagEmojiSelector("🇸🇨", "seychelles"))
        list.append(FlagEmojiSelector("🇸🇱", "sierra leone"))
        list.append(FlagEmojiSelector("🇸🇬", "singapore"))
        list.append(FlagEmojiSelector("🇸🇽", "sint maarten"))
        list.append(FlagEmojiSelector("🇸🇰", "slovakia"))
        list.append(FlagEmojiSelector("🇸🇮", "slovenia"))
        list.append(FlagEmojiSelector("🇸🇧", "solomon islands"))
        list.append(FlagEmojiSelector("🇸🇴", "somalia"))
        list.append(FlagEmojiSelector("🇿🇦", "south africa"))
        list.append(FlagEmojiSelector("🇰🇷", "south korea"))
        list.append(FlagEmojiSelector("🇸🇸", "south sudan"))
        list.append(FlagEmojiSelector("🇪🇸", "spain"))
        list.append(FlagEmojiSelector("🇱🇰", "sri lanka"))
        list.append(FlagEmojiSelector("🇧🇱", "saint barthelemy"))
        list.append(FlagEmojiSelector("🇸🇭", "saint helena"))
        list.append(FlagEmojiSelector("🇰🇳", "saint kitts and nevis"))
        list.append(FlagEmojiSelector("🇱🇨", "saint lucia"))
        list.append(FlagEmojiSelector("🇵🇲", "saint pierre and miquelon"))
        list.append(FlagEmojiSelector("🇻🇨", "saint vincent and grenadines"))
        list.append(FlagEmojiSelector("🇸🇩", "sudan"))
        list.append(FlagEmojiSelector("🇸🇷", "suriname"))
        list.append(FlagEmojiSelector("🇸🇿", "swaziland"))
        list.append(FlagEmojiSelector("🇸🇪", "sweden"))
        list.append(FlagEmojiSelector("🇨🇭", "switzerland"))
        list.append(FlagEmojiSelector("🇸🇾", "syria"))
        list.append(FlagEmojiSelector("🇹🇼", "taiwan"))
        list.append(FlagEmojiSelector("🇹🇯", "tajikistan"))
        list.append(FlagEmojiSelector("🇹🇿", "tanzania"))
        list.append(FlagEmojiSelector("🇹🇭", "thailand"))
        list.append(FlagEmojiSelector("🇹🇱", "timor leste"))
        list.append(FlagEmojiSelector("🇹🇬", "togo"))
        list.append(FlagEmojiSelector("🇹🇰", "tokelau"))
        list.append(FlagEmojiSelector("🇹🇴", "tonga"))
        list.append(FlagEmojiSelector("🇹🇹", "trinidad and tobago"))
        list.append(FlagEmojiSelector("🇹🇳", "tunisia"))
        list.append(FlagEmojiSelector("🇹🇷", "turkey"))
        list.append(FlagEmojiSelector("🇹🇲", "turkmenistan"))
        list.append(FlagEmojiSelector("🇹🇨", "turks and caicos islands"))
        list.append(FlagEmojiSelector("🇹🇻", "tuvalu"))
        list.append(FlagEmojiSelector("🇻🇮", "united states virgin islands"))
        list.append(FlagEmojiSelector("🇺🇬", "uganda"))
        list.append(FlagEmojiSelector("🇺🇦", "ukraine"))
        list.append(FlagEmojiSelector("🇦🇪", "united arab emirates"))
        list.append(FlagEmojiSelector("🇬🇧", "united kingdom"))
        list.append(FlagEmojiSelector("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "england"))
        list.append(FlagEmojiSelector("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "scotland"))
        list.append(FlagEmojiSelector("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "wales"))
        list.append(FlagEmojiSelector("🇺🇸", "united states"))
        list.append(FlagEmojiSelector("🇺🇾", "uruguay"))
        list.append(FlagEmojiSelector("🇺🇿", "uzbekistan"))
        list.append(FlagEmojiSelector("🇻🇺", "vanuatu"))
        list.append(FlagEmojiSelector("🇻🇦", "holy see"))
        list.append(FlagEmojiSelector("🇻🇪", "venezuela"))
        list.append(FlagEmojiSelector("🇻🇳", "vietnam"))
        list.append(FlagEmojiSelector("🇪🇭", "western sahara"))
        list.append(FlagEmojiSelector("🇾🇪", "yemen"))
        list.append(FlagEmojiSelector("🇿🇲", "zambia"))
        list.append(FlagEmojiSelector("🇿🇼", "zimbabwe"))
    }
}























