//
//  Emoji.swift
//  Swipe
//
//  Created by Jesus Andres Bernal Lopez on 3/29/18.
//  Copyright © 2018 Jesus Andres Bernal Lopez. All rights reserved.
//

import UIKit

class AnimalEmoji {
    
    var list = [AnimalEmojiSelector]()
    
    init(){
        list.append(AnimalEmojiSelector("🐶", "dog"))
        list.append(AnimalEmojiSelector("🐱", "cat"))
        list.append(AnimalEmojiSelector("🐭", "mouse"))
        list.append(AnimalEmojiSelector("🐹", "hamster"))
        list.append(AnimalEmojiSelector("🐰", "rabbit", "bunny"))
        list.append(AnimalEmojiSelector("🦊", "fox"))
        list.append(AnimalEmojiSelector("🐻", "bear"))
        list.append(AnimalEmojiSelector("🐼", "panda"))
        list.append(AnimalEmojiSelector("🐨", "koala"))
        list.append(AnimalEmojiSelector("🐅", "tiger"))
        list.append(AnimalEmojiSelector("🦁", "lion"))
        list.append(AnimalEmojiSelector("🐮", "cow"))
        list.append(AnimalEmojiSelector("🐷", "pig"))
        list.append(AnimalEmojiSelector("🐸", "frog"))
        list.append(AnimalEmojiSelector("🐵", "monkey"))
        list.append(AnimalEmojiSelector("🐔", "chicken"))
        list.append(AnimalEmojiSelector("🐧", "penguin"))
        list.append(AnimalEmojiSelector("🐦", "bird"))
        list.append(AnimalEmojiSelector("🐥", "chick"))
        list.append(AnimalEmojiSelector("🦆", "duck"))
        list.append(AnimalEmojiSelector("🦅", "eagle"))
        list.append(AnimalEmojiSelector("🦉", "owl"))
        list.append(AnimalEmojiSelector("🦇", "bat"))
        list.append(AnimalEmojiSelector("🐺", "wolf"))
        list.append(AnimalEmojiSelector("🐗", "boar"))
        list.append(AnimalEmojiSelector("🐴", "horse"))
        list.append(AnimalEmojiSelector("🦄", "unicorn"))
        list.append(AnimalEmojiSelector("🐝", "bee"))
        list.append(AnimalEmojiSelector("🐛", "bug"))
        list.append(AnimalEmojiSelector("🦋", "butterfly"))
        list.append(AnimalEmojiSelector("🐌", "snail"))
        list.append(AnimalEmojiSelector("🐚", "sea shell", "shell"))
        list.append(AnimalEmojiSelector("🐞", "ladybug"))
        list.append(AnimalEmojiSelector("🐜", "ant"))
        list.append(AnimalEmojiSelector("🦗", "cricket"))
        list.append(AnimalEmojiSelector("🕷", "spider"))
        list.append(AnimalEmojiSelector("🦂", "scorpion"))
        list.append(AnimalEmojiSelector("🐢", "turtle"))
        list.append(AnimalEmojiSelector("🐍", "snake"))
        list.append(AnimalEmojiSelector("🦎", "lizard"))
        list.append(AnimalEmojiSelector("🦖", "t-rex", "t rex", "tyrannosaurus rex"))
        list.append(AnimalEmojiSelector("🦕", "dinosaur"))
        list.append(AnimalEmojiSelector("🐙", "octopus"))
        list.append(AnimalEmojiSelector("🦑", "squid"))
        list.append(AnimalEmojiSelector("🦐", "shrimp"))
        list.append(AnimalEmojiSelector("🦀", "crab"))
        list.append(AnimalEmojiSelector("🐡", "blowfish"))
        list.append(AnimalEmojiSelector("🐠", "tropical fish"))
        list.append(AnimalEmojiSelector("🐟", "fish"))
        list.append(AnimalEmojiSelector("🐬", "dolphin"))
        list.append(AnimalEmojiSelector("🐋", "whale"))
        list.append(AnimalEmojiSelector("🦈", "shark"))
        list.append(AnimalEmojiSelector("🐊", "crocodile"))
        list.append(AnimalEmojiSelector("🐆", "leopard"))
        list.append(AnimalEmojiSelector("🦓", "zebra"))
        list.append(AnimalEmojiSelector("🦍", "gorilla"))
        list.append(AnimalEmojiSelector("🐘", "elephant"))
        list.append(AnimalEmojiSelector("🦏", "rhinoceros", "rhino"))
        list.append(AnimalEmojiSelector("🐫", "camel"))
        list.append(AnimalEmojiSelector("🦒", "giraffe"))
        list.append(AnimalEmojiSelector("🐃", "buffalo"))
        list.append(AnimalEmojiSelector("🐂", "ox"))
        list.append(AnimalEmojiSelector("🐏", "ram"))
        list.append(AnimalEmojiSelector("🐑", "sheep"))
        list.append(AnimalEmojiSelector("🐐", "goat"))
        list.append(AnimalEmojiSelector("🦌", "deer"))
        list.append(AnimalEmojiSelector("🐩", "poodle"))
        list.append(AnimalEmojiSelector("🐓", "rooster"))
        list.append(AnimalEmojiSelector("🦃", "turkey"))
        list.append(AnimalEmojiSelector("🕊", "dove"))
        list.append(AnimalEmojiSelector("🐀", "rat"))
        list.append(AnimalEmojiSelector("🐿", "chipmunk"))
        list.append(AnimalEmojiSelector("🦔", "hedgehog"))
    }
}
